"""empty message

Revision ID: 78ea0c4aceb5
Revises: 40b83e0b4f2b
Create Date: 2025-06-11 02:04:35.340189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ea0c4aceb5'
down_revision = '40b83e0b4f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('eye_color')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
