"""empty message

Revision ID: d37072582636
Revises: 78ea0c4aceb5
Create Date: 2025-06-11 04:53:15.232249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37072582636'
down_revision = '78ea0c4aceb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planets_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('_user_character_uc', ['user_id', 'character_id'])
        batch_op.create_unique_constraint('_user_planet_uc', ['user_id', 'planets_id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('_user_planet_uc', type_='unique')
        batch_op.drop_constraint('_user_character_uc', type_='unique')
        batch_op.alter_column('planets_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
